### ISSUE TITLE
WCancelButton incorrectly detecting changes

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#1063]
`WCancelButton` is incorrectly detecting changes even though there have not been any.

This can be replicated in the `client-app-sample` from [wcomponents-samples](https://github.com/BorderTech/wcomponents-samples) when creating an individual.

A version of this sample is running [here](http://wcomponents-bordertech.rhcloud.com/client/app)

**Comment by marksreeves** [comment]
I have isolated the cause of the "unsaved changes" warning. It is the `WDropdown` for the "Passport country" (similar conditions may apply for the other cached `WDropdowns`).

When this component is rendered the "selected" option has a value of `"1"`. When the `datalist` for that component is loaded the same option has a value of `""`. Therefore there is a change in the form as far as the client serialization code is concerned.

I have isolated this to a flaw in the Application. See https://github.com/BorderTech/wcomponents-samples/issues/10.

Closed: not a WComponents issue.
