### ISSUE TITLE
WTable action constraints not handling selected rows and pagination

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#1078]
A `WTable` with `row selection`, `dynamic pagination` and a `table action` with `constraints` does not cater for `rows` selected on `other` pages.

For example, if the `action` constraint requires at least one row to be selected and the selected row is not on the current page, the `action` button will display a message stating no rows have been selected.

**Comment by Jonno1809** [comment]
Fixed in PR #1402
