### ISSUE TITLE
Chrome form submit on ENTER with select elements

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1122]
Recent versions of Chrome (possibly others but not Firefox or IE, haven't tested Edge or Safari yet) will submit a HTML form if the user hits the `ENTER` key when a select element has focus if the select is either `multiple` or has a `size` attribute (i.e. anything other than a single select "dropdown" style select).

We do not yet implement `wc/ui/defaultSubmit` on select elements because they aren't supposed to do this. We had better extend `defaultSubmit` to allow for this _feature_.

**Comment by Likhasinh** [comment]
**Safari on iOS - Multi-dropdown and dropdown in ePLUS forms**
When the select element has focus and it's a single select style, the `ENTER` key logs out of application.

**Chrome on iOS - Multi-dropdown and dropdown in ePLUS forms**
When the select element has focus and it's a single select style, the `ENTER` key refreshes the page setting the focus to top of page.

**Comment by marksreeves** [comment]
We can simplify defaultSubmit to work with all form-associated elements based on https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

Note, however that the default action of pressing ENTER/RETURN of an input with type `file` is to open the file browser so we still need to exclude these from our defaultSubmit override. In addition the default behaviour of ENTER/RETURN applied to a checkbox is to submit and not to toggle the checked state.
