### ISSUE TITLE
Suggestions for improving usage of Size

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#1131]
Currently the ```Size``` enum is nested within the ```SpaceUtil``` class. Other than the ```Size``` enum the ```SpaceUtil``` class has utility methods that allow for converting between ```Size``` and ```int```. These methods are deprecated as is everything else in the class except the ```Size``` enum. Once the deprecated members of this class are removed, the API will have an enum wrapped in a class with no other members in the class.

I would like to propose that the ```Size``` enum be removed from the ```SpaceUtil``` class so that it is defined in its own file, and so ```SpaceUtil``` is not then a part of any public API.

I'd be happy to submit a PR if you all agree with these suggestions.

WDYT @jonathanaustin @marksreeves @Joshua-Barclay

**Comment by marksreeves** [comment]
@jonathanaustin: I think @JohnMcGuinness is on to something here. My original thought was to have a simple enum but added the helper methods just for backwards compatibility. I think that my design is flawed as it does leave us with a utility class when we really just want an enum. If we are going to change this though we need to get it done before 1.4 goes out of beta so I would like your input ASAP.

**Comment by marksreeves** [comment]
Resolved in #1141. Thanks John.
