### ISSUE TITLE
Client handlebars causes double request for images

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1158]
The way i18n is done in-client causes images to be requested twice. Not a big deal if images are cached but annoying and potentially costly for uncached images.

The current workaround is to turn on server rendering of handlebars. We should be able to do better than this.

To use the workaround set a property:

```
bordertech.wcomponents.template.render.mode=on
```

### Note:
Turns out this does not work in 1.3 as we do not test for server handlebars.

**Comment by marksreeves** [comment]
Partial workaround: handlebars server rendering is now on by default from #1156

**Comment by ricksbrown** [comment]
The correct solution to this, IMHO, is to embed all initial handlebars templates into script elements.
The template render is then responsible for processing these templates and building the page into the `<body>`

```
<script id="app1" type="text/x-handlebars-template">
    <div>{{someToken}}</div>
</script>
```
I tested this last year and it worked well.

**Comment by marksreeves** [comment]
Hey @ricksbrown . The only real problem with wrapping the page content in a script element is that XSLT will not escape character entities inside the content of a script element (at least not using Saxon 9).

So if the XML is, for example

``` xml 
<ui:option value="8">&lt;br/&gt;</ui:option>
```

and the expected HTML output is 

``` html
<option value="8">&lt;br/&gt;</option>
```

What Saxon outputs if the content is inside a script element (either using a simple `<script...` element or `<xsl:element name="script"...`) is:

``` html
<option value="8"><br/></option>
```

(See `com.github.bordertech.wcomponents.examples.WDropdownOptionsExample`)

Whilst this may seem rather pointless and silly it has real impact on some use cases. I have been able to emulate the intent of a script element using a div thus:

``` xslt
<div id="{generate-id(.)}" hidden="hidden" style="display:none;">
  <xsl:apply-templates/>
</div>
```

This use of a hidden div as a wrapper is sub-optimal but does get around the initial issue as images inside a hidden container are not requested.

Thoughts?
