### ISSUE TITLE
Add getChildren() to Container API

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#116]
Adding this method to the Container API would allow simpler iteration using the enhanced for loop.

For example, in short it would turn this:

```
if (component instanceof Container) 
{
    Container container = (Container) component;
    int childCount = container.getChildCount();

    for (int i = 0; i < childCount; i++) 
    {
        WComponent child = container.getChildAt(i);
        // Do something with child....
    }
}
```

into this:

```
if (component instanceof Container) 
{
    for(WComponent child : ((Container)container).getChildren())
    {
        // Do something with child....
    }
}
```

The return type would be List<? extends WComponent>, and implementations should return an unmodifiable List. If there are no children then an empty list should be returned.

Importantly, the existing 3 methods on Container are all provided by List:

size() -> getChildCount()
get(int i) -> getChildAtIndex()
indexOf(Object o) -> getIndexOfChild(WComponent child)

If this is accepted then the existing methods on Container could/should be deprecated?

**Comment by jonathanaustin** [comment]
This looks like a good API change and it makes sense.

At this stage I think we could hold off deprecating the other methods as they can be viewed as "helper" methods.

Looks good.
