### ISSUE TITLE
Build fails on OS X when using JDK8 u60

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#125]
The build is failing on OS X using JDK8 u60. The test that fails is DetectorsTest in the findbugs plugin project. The exception being returned is ArrayIndexOutOfBoundsException. This has been replicated by @ricksbrown.

**Comment by marksreeves** [comment]
Findbugs 3.x is required for Java 8 support and we are currently using 1.3.9. This will require a re-coding of the findbugs plugin - specifically edu.umd.cs.findbugs.DetectorsTest and edu.umd.cs.findbugs.detect.CheckExpectedWarnings. @jonathanaustin feel like taking this one on?

**Comment by marksreeves** [comment]
@jonathanaustin Can you please take a look at the wcomponents-findbugs-plugin in the light of the above and enlighten us as to whether we fix this plugin or delete it and revert to vanilla findbugs?
