### ISSUE TITLE
WTimeoutWarning client code i18n failure

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1281]
under some circumstances the timeout warning dialog will call i18n before i18n has been initialised. This can be replicated using the timeout options example.

@ricksbrown want to take a look?

**Comment by ricksbrown** [comment]
Wow, I would have thought it would be ready by the time a session times out. I'll take a look.

**Comment by marksreeves** [comment]
This may not be an issue in a real application. I hit it a few times testing timeout warning but that example does not contain anything else which is internationalised.
