### ISSUE TITLE
WTree (htree) loses selections when branches are loaded using AJAX

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1317]
When a WTree is in htree mode and its branches are loaded via AJAX there is a race between the ajax load and setting selection but selection always loses (QC 168164).

1. Open WTreeExample
2. Set options "use htree" and set "Expand mode" to "DYNAMIC"
3. Open a branch (eg "Joe Bloggs")

### Expect

That the branch becomes selected, opens and the branch items are displayed

### Actual

The branch opens, becomes selected, the tree reloads with the open branch items and the branch is no longer selected.

When running this scenario through a JavaScript debugger we can see the Ajax trigger is firing before the branch is made selected.

### More clues?

Selection is undertaken by module `wc/ui/menu/treeitem`, the ajax trigger on open is done by module `wc/ui/menu/tree` but both are ultimately controlled by shed subscribers. This one ain't quite so easy as it at first seems as it comes down to event order in shed subscribers.

**Comment by ricksbrown** [comment]
I think this is a lot more mundane than we first thought...
The selection of htree branches is _never_ honoured by the server. Even in client mode, when you round trip the selection is always lost.

**Comment by marksreeves** [comment]
The example (`com/github/bordertech/wcomponents/examples/WTreeExample`) _seems_ to honour selection on round trip in client mode.

**Comment by ricksbrown** [comment]
So actually the issue is that the server side code is rejecting state changes when we are making an AJAX request to open a branch.

The way forward is to cease replacing the entire tree when we do AJAX and instead actually fetch just the content of the opening branch.
