### ISSUE TITLE
Building descendant themes using a package

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#1318]
* When a theme is built which inherits directly from `wcomponents-theme` (no inherit.txt) it uses the maven artefact of the theme source.
* When a theme inherits from another theme it can use a path or a zip to access the source of the parent theme. 

When seems to be missing is the ability to inherit from a package (Maven or npm). Maybe this could be added quite easily but is it worthwhile? Should we re-think the whole theme inheritance thing?

@ricksbrown opinions?

**Comment by ricksbrown** [comment]
Yes the whole thing needs to be rethunk.
We have simplified many of the original concerns that forced us down a custom, build-time theme inheritance system.

Importantly:
* property driven themes are now gone
* xslt overrides no longer "a thing"

**Comment by marksreeves** [comment]
Closing this. Will raise a new issue to convert theme build to remove Ant.
