### ISSUE TITLE
Enhance the Marginable interface to reflect margin API in CSS

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#1371]
I would like to suggest enhancing the ```Marginable``` interface with methods that mirror the CSS margin API.

Specifically, I would like to suggest deprecating the ```setMargin(Margin margin)``` method and adding the following methods:

```void setMargin(Size all)```
```void setMargin(Size topBottom, Size leftRight)```
```void setMargin(Size top, Size leftRight, Size bottom)```
```void setMargin(Size top, Size right, Size bottom, Size left)```
```Size getAllMargin()```
```Size getTopMargin()```
```Size getRightMargin()```
```Size getBottomMargin()```
```Size getLeftMargin()```

Adding this enhancement would, eventually, remove the Margin class from WComponent's Java API. 
WDYT @marksreeves @jonathanaustin

**Comment by marksreeves** [comment]
I like the idea of making the individual sides of margins easier to manipulate and I am not averse to making the Margin API similar to the CSS margin shorthand syntax (though I am also cognisant of, and not in total disagreement with, the notion that CSS shorthand is a bit rubbish).

@JohnMcGuinness Whilst I like the idea of `setMargin(Size)` etc I would like to know what value you see in removing `setMargin(Margin)` other than a quieter API?

**Comment by JohnMcGuinness** [comment]
From a code perspective its annoying to create them. 
I think that 

```
import static com.github.bordertech.wcomponents.Size.*;
...
myMarginable.setMargin(MEDIUM);
myMarginable.setMargin(MEDIUM, LARGE); 
myMarginable.setMargin(MEDIUM, LARGE, SMALL); 
```

is easier to read, and write, than

```
import static com.github.bordertech.wcomponents.Size.*;
...
myMarginable.setMargin(new Margin(MEDIUM));
myMarginable.setMargin(new Margin(MEDIUM, LARGE, MEDIUM, LARGE));
myMarginable.setMargin(new Margin(MEDIUM, LARGE, SMALL, LARGE));
```

What benefit does having the instances of ```Margin``` give? I think the abstraction of having ```Margin``` objects is redundant.

The information I'm trying to convey is the value of the margin attributes, which in WComponents  happens to be of type ```Size```. I can do that without needing the additional abstraction of the ```Margin``` class. Also, if ```Margin``` is not used there are less objects being created, ```ComponentsModel```s may have some extra attributes, though.

@marksreeves

**Comment by JohnMcGuinness** [comment]
I'm looking at this now. I would like to use default methods in the ```Marginable``` interface to reduce code duplication. This is is a Java 8 feature. What is the minimum Java version that WComponents can currently be used with.

🤔 

@marksreeves @jonathanaustin

**Comment by JohnMcGuinness** [comment]
Parent pom indicates Java 8, should have checked first sorry.
