### ISSUE TITLE
Windows Phone Support

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#141]
IE11 on Windows Phone 8.1 has lost all ability to perform client side XSLT. WComponents relies heavily on this technology.

Currently the only workaround is to use another browser (Opera Mini works) on Windows Phone 8.1.

We could detect this user agent and perform server side transforms BUT it may not be worth it because:
1. There is a free workaround.
2. This will only affect a tiny portion of users.
3. Windows 10 mobile is soon to replace Windows 8.1 mobile.

I have installed Windows 10 (Mobile Insider Preview) on a Lumia 925 and can confirm this problem ceases to exist for the best possible reason, Internet Explorer is gone! Microsoft Edge is the only browser visible on the home screen and even searching installed apps does not find Internet Explorer, yay!

Yes, Microsoft Edge on Windows 10 (Mobile Insider Preview) handles XSLT just fine.

In the short term Windows 10 should prevent this from becoming an issue.
In the medium term we are moving away from client side XSLT probably to [Custom Elements](http://www.w3.org/TR/custom-elements/)

**Comment by marksreeves** [comment]
Agreed. 

Client side XSLT was available in Windows mobile 8 and early versions of 8.1 so it was removed during an update cycle. Expect negligible impact.
