### ISSUE TITLE
ui:skiplinks transformed to html:skiplinks in default theme

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#1420]
In the default theme this

```xml
<ui:skiplinks/>
```

becomes this

```html
<skiplinks></skiplinks>
```

which is not a native HTML element nor is it a legit custom element.

**Comment by marksreeves** [comment]
This is picking up the default element transform which is for HTML elements. It does a copy and apply. The template match for `ui:skiplinks` appears to be missing. It used to have a cross-element lookup which is not reliable as it requires all elements to be present in the current XML so didn't work with ajax.

We can either remove the skiplinks support (it is only required if proper keymapping is not applied) or transform the `ui:skiplinks` to a placeholder lement and populate it using javascript.

SkipLinks could be implemented using a template if required - that way they can be in their proper place at the top of an application even before any header. If skiplinks are applied they should be the first focusable elements in a view and there is no way to enforce that in the current implementation.
