### ISSUE TITLE
WTable setSort(column, ascending) does not actually sort the table

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#147]
In the constructor or during an active user session a sort order can be defined on a WTable by calling:
`WTable.setSort(column, ascending);`

A consuming application would expect this to actually sort the data in the table when the component is rendered.

At the moment the only affect of invoking this method is that the table column will *appear* to be sorted in the client (both in the HTML and displayed in the UI with the sorting arrow) but the data will not actually be sorted.

`WTable.preparePaintComponent(request)` should check whether a sort order has been defined and if so sort the table prior to rendering.

**Comment by jonathanaustin** [comment]
<code>WTable.setSort(column, ascending)</code> is a protected method which is intended more for internal use. It is used to indicate which column is the currently sorted column but does not sort the data.

There is a public method <code>WTable.sort(column, ascending)</code> that allows a project to sort the data and also set the sort column.

If you do require the data to be loaded into a table and have a default sort, you can do this in the <code>preparePaintComponent(Request)</code> method and call <code>WTable.sort(column, ascending)</code>.

    protected void preparePaintComponent(final Request request)
    {
       super.preparePaintComponent(request);
        if (!isInitialised())
        {
            sort(1, true);
            setInitialised(true);
        }
    }

As "sorting" the data can be a heavy process we don't want to do this every preparePaint.

FYI - There is also another public method <code>WTable.handleDataChanged()</code> that can be called when the underlying data of the table has changed. This will "resort" the data (if it was previously sorted) and put the table onto the correct page.

**Comment by Joshua-Barclay** [comment]
The JavaDoc makes this clear, had we actually read it:

    `/**
     * For rendering purposes only - has no effect on model.
     * 
     * @param index the sort column index, or -1 for no sort.
     * @param ascending true for ascending order, false for descending
     */
    protected void setSort(final int index, final boolean ascending)`

I've had a look at the BR3 code base and it appears the method is only used internally - could it be made private to ensure no further confusion? A private method aligns with the description you provided:
>WTable.setSort(column, ascending) is a protected method which is intended more for internal use. It is used to indicate which column is the currently sorted column but does not sort the data.

**Comment by jonathanaustin** [comment]
Its always hard to decide "private" vs "protected". To quote "Effective Java - Second Edition" (page 89):-

> So how do you decide what protected members to expose when you design a class for
> inheritance? Unfortunately, there is no magic bullet. The best you can do is to think hard,
> take your best guess, and then test it by writing subclasses. You should expose as few
> protected members as possible, because each one represents a commitment to
> an implementation detail. On the other hand, you must not expose too few, as a missing
> protected member can render a class practically unusable for inheritance.

As the public sort method <code>WTable.sort(column,ascending)</code> and public refresh methods like <code>WTable.handleDataChanged()</code> can be overridden, there is a good chance the subclasses might want/need to make use of the protected method <code>WTable.setSort(column, ascending)</code>.

**Comment by ricksbrown** [comment]
[permalink to version of WTable in question](https://github.com/BorderTech/wcomponents/blob/8497606a6535b115c4d74ffa2e6fefd6e5056b7b/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/WTable.java#L1056)

**Comment by marksreeves** [comment]
Looks like we have reached a consensus. I am closing this "invalid" as there is nothing to fix:

> The JavaDoc makes this clear, had we actually read it

If you decide after further discussion to re-address it, re-open the issue and I will remove the label. Yell at me directly if you disagree with this but I see no value in keeping these old issues open if we have no intention of amending the API.
