### ISSUE TITLE
Tables: In column filter looks like the column can also be sorted.

### ISSUE THREAD

**Issue by Likhasinh** [BorderTech/wcomponents#1472]
Usability-The implementation of in column filter makes it look like the column can also be sorted. 
Design-The drop down down menu icon looks the same as sort descending icon.

**Comment by marksreeves** [comment]
There is no column filter. There is, however a filter example. The issue appears to be that the sort icon and submenu open icon are the same. 

WHat would you suggest would be an appropriate image for each?
