### ISSUE TITLE
General Enquiry for help.

### ISSUE THREAD

**Issue by Zynde** [BorderTech/wcomponents#1482]
Hi,

I'm looking to find a contact to see if I can discuss interacting with the Australian Online IMMI website. This wcomponents appears to be the framework used for that system. I realise that this might not be the best place to ask but I've not located any other contact details.

Hoping someone can help. Thanks.

**Comment by marksreeves** [comment]
The web site to which you refer is merely a consumer of WComponents. We have no influence or information regarding any consumers. I suggest you contact the site owner using their contact details online. There is a link at he bottom of their home page.
