### ISSUE TITLE
WAbbrText API and JavaDoc ambiguities

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#157]
The members of WAbbrText contain references to abbr, abbrText, get/setAbbrText and various JavaDoc comments which are misleading due to ambiguity. 

The abbreviation is represented by the text of the component. The member `abbr` is actually the full (expanded) text represented by the abbreviation.

I suggest: 

1. fix the JavaDoc to remove the ambiguities and improve its usefulness;
2. rename the public method arguments which refer to abbr to remove this source of ambiguity;
2. deprecate the public methods `getAbbrText` and `setAbbrText` in favour of `getExpandedText` and `setExpandedText` and refactor internal calls to these methods;
3. refactor `WAbbrText.AbbrTextModel.abbr` to `WAbbrText.AbbrTextModel.expanded`.

I am happy to undertake these if the Java guardians are happy. @jonathanaustin?

**Comment by jonathanaustin** [comment]
Yes, I agree. WAbbrText is ambiguous.

As the "expanded" text is often referred to as the "tooltip", why not use the "tooltip" from AbstractWComponent to store the "description" and deprecate set/getAbbrText().

This will allow you to remove the AbbrTextModel (Will have to flag this as an API change in the change log in case any projects have expanded this model.)

**Comment by marksreeves** [comment]
That makes perfect sense. Will implement.
