### ISSUE TITLE
WTabset.setActiveTab should handle WTab as parameter

### ISSUE THREAD

**Issue by sgardner0** [BorderTech/wcomponents#1626]
I expected WTabSet.setActiveTab(Wcomponent) to work if I pass the WTab to activate. Instead it expects the content bizarrely.

I suggest the WTabSet.setActiveTab(WComponent content) should check if (content instanceof WTab) then get the index of that tab, else do as usual. So it works for both WTab and it's content.

Thanks Sonja

**Comment by JohnMcGuinness** [comment]
@jonathanaustin happy to look at this. Should it just be a method that takes a WTab gets the content and calls the existing method? Or did you have something else in mind?
