### ISSUE TITLE
How would you do a login Wpanel or dialog ?

### ISSUE THREAD

**Issue by richardh65** [BorderTech/wcomponents#1686]
Hi 

I wanted to use to use wcomponents to build an app but I can’t work out how to create a login page that I can hide once I have checked the credentials.

I have tried making the panel invisible but that’s not working .

I also tried to do it as a dialog but I couldn’t have the dialog appear when the page first loads.

Do you have an example app that has a login page  ?
Preferably one that makes the user login first thing.

Thanks heaps guys for any help.
Regards 
Richard

**Comment by marksreeves** [comment]
I would not use a WDialog for a login page (though one can have it open on load) - but I would not use WDialog for anything.
The login page could simply be a card in the cardmanager which is only the visible card when the user is not logged in.

**Comment by richardh65** [comment]
Thanks Mark

That works really well.

Appreciate you getting back to me so quickly.

Regards
Richard


Sent from my iPhone

On 26 Nov 2019, at 12:59 pm, Mark Reeves <notifications@github.com> wrote:

﻿

I would not use a WDialog for a login page (though one can have it open on load) - but I would not use WDialog for anything.
The login page could simply be a card in the cardmanager which is only the visible card when the user is not logged in.

**Comment by richardh65** [comment]
Hi Mark,


Merry Xmas.


I have another WComponents question.


Is it possible to a WLink to a table ?

I can add a link as a table column, which show up, but the link doesn't go to the link address (which is what is showing on the table).


[cid:part1.E79D2C82.302AB430@hotmail.com]


activeWebsitesTable.addColumn(new WTableColumn("Link", new WLink()));

SimpleBeanBoundTableModel model = new SimpleBeanBoundTableModel(
                    new String[]{"linkSite" });
            activeWebsitesTable.setTableModel(model);


Regards

Richard



On 27/11/2019 9:15 am, richardh65_@hotmail.com<mailto:richardh65_@hotmail.com> wrote:
Thanks Mark

That works really well.

Appreciate you getting back to me so quickly.

Regards
Richard


Sent from my iPhone

On 26 Nov 2019, at 12:59 pm, Mark Reeves <notifications@github.com><mailto:notifications@github.com> wrote:

﻿

I would not use a WDialog for a login page (though one can have it open on load) - but I would not use WDialog for anything.
The login page could simply be a card in the cardmanager which is only the visible card when the user is not logged in.

**Comment by marksreeves** [comment]
It is certainly possible. @jonathanaustin Can you field this one please: adding a WLink as data in a WTabkeColumn

**Comment by jonathanaustin** [comment]
When a `WLink` is bound to a bean, the bean property is only used as the text of the link. So setting the `url` can be achieved in a number of different ways.

Here is some sample code on using (1) the WLink text as the Url, (2) a seperate text and url from the bean and (3) overriding `preparePaintComponent` to manually set the values from the bean. As a FYI, using a bean property of "." means the entire bean is passed to the component.

```
WTable table = new WTable();
// Use the text as the URL
WLink link = new WLink() {
    @Override
    public String getUrl() {
        return getText();
    }
};
// Bind the entire "bean" by setting "." as the property and then use the url and description from the bean
WLink link2 = new WLink() {
    @Override
    public String getText() {
        return ((MyPojo) getBean()).getDesc();
    }

    @Override
    public String getUrl() {
        return ((MyPojo) getBean()).getUrl();
    }
};
// Or override initializing the WLink and set the values from the bean
WLink link3 = new WLink() {
    @Override
    protected void preparePaintComponent(final Request request) {
        super.preparePaintComponent(request);
        if (!isInitialised()) {
            MyPojo bean = (MyPojo) getBean();
            setText(bean.getDesc());
            setUrl(bean.getUrl());
            setInitialised(true);
        }
    }

table.addColumn(new WTableColumn("Link URL Only", link));
table.addColumn(new WTableColumn("Link Desc and Url", link2));
table.addColumn(new WTableColumn("Link Init from Bean", link3));

// Using a bean property of "." means the entire bean is passed to the component
SimpleBeanBoundTableModel model = new SimpleBeanBoundTableModel(new String[]{"url", ".", "."});
table.setTableModel(model);
add(table);


// Setting sample data
table.setBean(Arrays.asList(new MyPojo("http://www.example.com", "mylink")));
```

The sample bean:
```
public static class MyPojo implements Serializable {

    private String url;
    private String desc;

    public MyPojo(final String url, final String desc) {
        this.url = url;
        this.desc = desc;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(final String url) {
        this.url = url;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(final String desc) {
        this.desc = desc;
    }
}
```

Hope this helps...

**Comment by richardh65** [comment]
Thanks for that

I will give it a try.

Regards
Richard


Sent from my iPhone

On 8 Jan 2020, at 3:23 pm, Jonathan Austin <notifications@github.com> wrote:

﻿

When a WLink is bound to a bean, the bean property is only used as the text of the link. So setting the url can be achieved in a number of different ways.

Here is some sample code on using (1) the WLink text as the Url, (2) a seperate text and url from the bean and (3) overriding preparePaintComponent to manually set the values from the bean. As a FYI, using a bean property of "." means the entire bean is passed to the component.

WTable table = new WTable();
// Use the text as the URL
WLink link = new WLink() {
    @Override
    public String getUrl() {
        return getText();
    }
};
// Bind the entire "bean" by setting "." as the property and then use the url and description from the bean
WLink link2 = new WLink() {
    @Override
    public String getText() {
        return ((MyPojo) getBean()).getDesc();
    }

    @Override
    public String getUrl() {
        return ((MyPojo) getBean()).getUrl();
    }
};
// Or override initializing the WLink and set the values from the bean
WLink link3 = new WLink() {
    @Override
    protected void preparePaintComponent(final Request request) {
        super.preparePaintComponent(request);
        if (!isInitialised()) {
            MyPojo bean = (MyPojo) getBean();
            setText(bean.getDesc());
            setUrl(bean.getUrl());
            setInitialised(true);
        }
    }

table.addColumn(new WTableColumn("Link URL Only", link));
table.addColumn(new WTableColumn("Link Desc and Url", link2));
table.addColumn(new WTableColumn("Link Init from Bean", link3));

// Using a bean property of "." means the entire bean is passed to the component
SimpleBeanBoundTableModel model = new SimpleBeanBoundTableModel(new String[]{"url", ".", "."});
table.setTableModel(model);
add(table);


// Setting sample data
table.setBean(Arrays.asList(new MyPojo("http://www.example.com", "mylink")));


The sample bean:

public static class MyPojo implements Serializable {

    private String url;
    private String desc;

    public MyPojo(final String url, final String desc) {
        this.url = url;
        this.desc = desc;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(final String url) {
        this.url = url;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(final String desc) {
        this.desc = desc;
    }
}


Hope this helps...
