### ISSUE TITLE
Enable server side XSLT by default

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#174]
This is a small step on the road to replacing XSLT with Custom Elements (Web Components).
It also accepts the fact that browser vendors have lost interest in XML / XSLT. It is common for us to come across issues that only occur on HTML pages generated by XSLT, for example:

- Terrible memory leaks in IE8 [when page generated by XSLT](https://support.microsoft.com/en-us/kb/2032595)
- Firefox performance API completely broken in pages generated by XSLT [but XSLT gets low priority](https://bugzilla.mozilla.org/show_bug.cgi?id=804069#c8):

> Honestly, I don't know of anyone not working on something more important. XSLT is not seeing a whole lot of usage on the web.

- Original Android browser did not do XSLT at all.
- Chrome's implementation of Web Components [throws errors if the page is generated by XSLT](https://code.google.com/p/chromium/issues/detail?id=551089).
- Windows Phone 8.1 lost all ability to do client side XSLT #141 

Is XSLT a powerful transformation engine that ships with every major browser out of the box? Yes.
Has it seen massive uptake and support? No.

Ultimately I believe this is a case of the [principle of least power](http://www.w3.org/2001/tag/doc/leastPower) - people prefer JSON instead of XML not **despite** it being less powerful but **because** it is less powerful.

It's time to demote it, move it to the server and start replacing it with plain old HTML and HTML Custom Elements.

**Comment by marksreeves** [comment]
I have to agree despite client XSLT being the best technical solution and excellent for distributed processing. JSON is just so [REDACTED] mouse as a technical solution - ajax is ajax and not ajat! However, I know I am whistling into the wind.
