### ISSUE TITLE
Labels on WMultiDropdown

### ISSUE THREAD

**Issue by SteveHarney** [BorderTech/wcomponents#1760]
I am just wondering if labels could be added to WMultiDropdowns i am currently deploying a snippet of code similar to below.   

          String[] DATA = { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j" };
            WFieldLayout layout = new WFieldLayout();
            add(layout);
            final WMultiDropdown dropdown = new WMultiDropdown(DATA);
            layout.addField("multi-dropdown 1", dropdown);

This is producing the below html with a hidden label stating "This component requires a label"

<fieldset aria-atomic="false" aria-relevant="additions removals" id="_1a1" class="wc-multidropdown wc_mfc wc_noborder" data-wc-max="5">
<legend class="wc-moved-label">multi-dropdown 1<i aria-hidden="true" class="fa fa-asterisk">
</i>
</legend>
<ul class="wc_list_nb wc-vgap-sm">
<li>
**<label for="_1a1d1e20-1" class="wc-off wc-err">This component requires a label</label>**
<select id="_1a1d1e20-1" name="_1a1">
<optgroup label="ddd">
<option value="1" selected="">a</option>
<option value="2">b</option>
....

**Comment by marksreeves** [comment]
Confirmed. The message @SteveHarney is seeing is inserted by an a11y helper when debug mode is on.

**Comment by marksreeves** [comment]
XSLT error. When rendering the default (hidden) label for each option in a WMultiDropdown the XSLT uses value of @title but the title attribute is an attribute of the multi-dropdown component, not of the option being rendered.
