### ISSUE TITLE
com.github.bordertech.wcomponents.AbstractWComponentTestCase.assertAccessorsCorrect does not work with setter Serializable args

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#188]
1. Create a JUnit to test accessors for which the setter has a Serializable argument;
2. use the helper `com.github.bordertech.wcomponents.AbstractWComponentTestCase.assertAccessorsCorrect` to test the accessors;
3. the JUnit fails unable to find setter;

Example
``` java
// getter
/**
 * {@inheritDoc}
 */
@Override
public String getHtmlClass() {
    ComponentModel model = getComponentModel();
    return I18nUtilities.format(null, model.getHtmlClass());
}

// setter
/**
 * {@inheritDoc}
 */
@Override
public void setHtmlClass(final String text, final Serializable... args) {
    ComponentModel model = getOrCreateComponentModel();
    model.setHtmlClass(text, args);
}

// JUnit
@Test
public void testHtmlClassAccessors() {
    assertAccessorsCorrect(new SimpleComponent(), "htmlClass", null, "foo", "bar");
}
```

Output
```
Caused by: java.lang.NoSuchMethodException: Property 'htmlClass' has no setter method in 
class ...
```

**Comment by jonathanaustin** [comment]
AbstractWComponentTestCase.assertAccessorsCorrect now works with variable arguments on the setter methods.

If a setter method on the component has a variable argument, then an array of the variable argument type needs to be provided via the setterArgs parameter on the assertAccessorsCorrect method.

For example, if the variable argument is a type "Serializable" then the setterArgs parameter would be set as "new Serializable[]{}". Values can also be passed in via the array.

For example....

```java
@Test
public void testMessageAccessors() {
 assertAccessorsCorrect(new WMenuItem(""), "message", null, "A", "B", new Serializable[]{});
}
```
