### ISSUE TITLE
WComponents performance - two-phase approach generates unnecessary processing

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#192]
The WComponents servlet processes requests with a two-phase approach:

``` Java
ServletUtil.processRequest(HttpServletHelper, WComponent, InterceptorComponent)
{
    synchronized (uic)
    {
        // Process the action phase.
        helper.processAction();

        // Process the render phase.
        helper.render();
    }
}
```

The current design is for these two phases to be completely independent in terms of the user context. The context is cleared at the end of the `helper.processAction();` method:

``` Java
finally
{
    UIContextHolder.reset();
}
```

After this is done each component has lost its component model state and the scratch map has been cleared.

As a result of the scratch map being cleared every component that relies on a BeanProvider will make two requests for each POST; one for the action phase and one for the render phase.

Is this design necessary? The extra step of discarding and recreating the UserContext between the two phases adds overhead and complexity to the framework.

The most significant issue is that the scratch map is cleared which removes the in-request cache of beans. This will possibly double the response time of a very common pattern (setting a `BeanProvider` to retrieve the current data from the database when processing/rendering each request).

@jonathanaustin what are your thoughts? Is there a significant reason why the design works this way?

**Comment by jonathanaustin** [comment]
The history of this pattern is due to supporting "portal" and its two phase lifecycle "action" and "render".

We have looked at changing this before but there is potentially a large impact to projects that "expect" this behaviour, or get "unexpected" behaviour due to this.

What might be good is to introduce a runtime parameter that can opt into this behaviour and allow for backward compatablity.

**Comment by marksreeves** [comment]
@jonathanaustin as this is a genuine performance issue *and* it effects most (all?) current consumers as there are none using pre-1.0.1 internal versions of WComponents _and_ Websphere Portal can we schedule this change for some time in the first half of this year and start an advertising campaign? The default should be remove the two stage processing with an opt in if Portal support is required. Can WComponents tell if it requires this two stage processing for Portal? Magic is always good.

**Comment by marksreeves** [comment]
Would be nice to get it in the next release but it ain't going to happen now.

**Comment by marksreeves** [comment]
@jonathanaustin Any info on the status of this?

**Comment by jonathanaustin** [comment]
Have modified `UIContext` to hold a new `scratch map` that has `request` scope.

The current `scratch map` has `phase` scope, which means it gets cleared out after each phase of the `WComponents` lifecycle (ie `Process actions` and `Render`).

The new request scope scratch map allows `components` to hold onto values across `phases`. However, components must not rely on these values being held in the request scope and must be able to recalculate their values if necessary.

`WBeanComponent` has been changed that when a `BeanProvider` is being used it can now use the new request scope scratch map. To opt into this functionality set the runtime parameter `bordertech.wcomponents.bean.provider.request.scope.enabled` to true.
