### ISSUE TITLE
Issue with WTable sort followed by WCancelButton click

### ISSUE THREAD

**Issue by evansmatthew** [BorderTech/wcomponents#239]
I have a page that has a WTable and WCancelButton.

After performing a sort on a WTable column, when the user then clicks the Cancel button, they are presented with a dialog stating "the page has unsaved changes - would you like to dicard? yes/no."

This makes no sense to the user, as they haven't changed any input fields. 

Please fix :)

**Comment by ricksbrown** [comment]
@evansmatthew Thanks for raising this. I can confirm this is a WComponents issue. The whole "unsaved changes" feature is quite a nightmare, far more complicated than one would expect.

**Comment by marksreeves** [comment]
This bug is based on the sort buttons having a name/value pair. We could take this opportunity to implement column sort based on the [HTML table sorting model](https://html.spec.whatwg.org/multipage/tables.html#table-sorting-model) and remove our completely custom sorting model.

**Comment by ricksbrown** [comment]
HTML5 to the rescue. Love it! Let's do it this way, much more work but it's fixed for good.

**Comment by marksreeves** [comment]
I'll take this: most of the mucking about is in the transformations.
