### ISSUE TITLE
Clickjacking is a risk in WComponents

### ISSUE THREAD

**Issue by evansmatthew** [BorderTech/wcomponents#240]
WComponents needs to return the X-Frame-Options attribute in the HTTP Response header, with a value of DENY.

Also consider setting X-Content-Type-Options to nosniff.

**Comment by marksreeves** [comment]
Not quite so binary as @evansmatthew has described as there are a few other options and side effects which need to be taken into account in a truly abstract UI framework. 

We need to take it on board though as it is a genuine security concern. @JohnMcGuinness how would you feel about taking a look at this?

**Comment by JohnMcGuinness** [comment]
@marksreeves  I'll have a go. Might need some guidance though.

**Comment by marksreeves** [comment]
@JohnMcGuinness of course - we're here for you. 

The thing that immediately spring to my mind is to research X-Frame-Options. It is generally supported but my quick look at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) yesterday gave no info about support in mobile browsers. A more wide-ranging survey of click jacking mitigation techniques is warranted. If we need to set new HTTP headers there are plenty of examples already in the Java code base and I defer to @jonathanaustin as to where they might best go. 

The important thing is that any HTTP header should default to most restrictive but allow override (so, for example, if we end up setting X-Frame-Options we would default to `DENY` but allow it to be set to any allowed value if the application warrants it - maybe an app is to be served in a frame for some reason so it may be set to `SAMEORIGIN` or even `ALLOW-FROM` if the app can guarantee support in consuming clients).

**Comment by marksreeves** [comment]
@JohnMcGuinness have you had a chance to look at this? If not let me know and I will take it over.

**Comment by JohnMcGuinness** [comment]
@marksreeves I've not had a chance. I'll hand it back to you.
