### ISSUE TITLE
AJAX file upload not working in FF42 on Mac OSX

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#245]
Works everywhere else!
Probably a FF issue.

**Comment by marksreeves** [comment]
Drag & drop works, selecting from browse button doesn't unless a file has already been uploaded via d&d.

**Comment by marksreeves** [comment]
OK, I have found one more scenario where I can reliably reproduce this issue so I am going to set the bug label and schedule a fix. 

1. In Firefox load the Multi-file Ajax example in the wcomponent-examples-lde;
2. do not focus anything;
3. click on the file upload "Browse..." button and choose a file.
  * **Expect**: file is uploaded
  * **Actua**l: Input value set but file not uploaded.

The file upload will work after it has been focussed with the keyboard, so we have a bootstrapping issue.
