### ISSUE TITLE
WComponents configuration should move towards more 'standard' methods of configuration

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#249]
I think most JEE developers are familiar with the concept of configuring their application via XML or Annotations. Where the annotation config can be overriden by XML. 

I think, but I am happy to be disproved, that few if any web frameworks use properties files as their primary means of configuration.

I would like to propose moving WComponents in the direction of favouring Annotations/XML as its primary means of configuration.

As a first step I would like to add the WServletConfiguration annotation. An example is below:

```
@WServletConfiguration( ui = MyApp.class)
public class MyWSerlet extends WServlet {
}
```

One benefit of this is that it is type safe. At compile time if the developer enters a value for `ui` that is not a subclass of `WCompnent` or maybe `WApplication` their IDE will tell them.

Also it obviates the need for the developer to be aware of `UIRegistry` and implement the `getUI()` method.

But above all it's simple, and makes it easier for a beginner to get started. I like API's that are simple.

WDYT @jonathanaustin @ricksbrown @marksreeves @Joshua-Barclay

**Comment by jonathanaustin** [comment]
Totally agree that we should look at moving in this direction.

An item we have had on our "todo" list for a long time is making WServlet easier to use. One way we thought was to make WServlet take an init parameter that defines the "application UI" class. The getUI method could look for this parameter, create an instance of the class and "register" it.

Using this parameter also means a project would not even have to create their own WServlet class.

But it would be awesome if we could create an annotation that projects can use on their WApplication class that setups the web servlet and registers it at the same time. Not sure if this could be done as the @WebServlet annotation does expect the class to extend HttpServlet. Maybe the new annotation could somehow link out to the WServlet class and set the init parameter to the WApplication class.

But...Annotations are definitely the way to go though.
