### ISSUE TITLE
Improve loading a WSubMenu via AJAX

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#250]
At the moment, when a WSubmenu is loaded via "AJAX" it requires all its child menu items to already be added. 

It would be more flexible if a WSubmenu was not required to have its "children" added until the submenu is opened.

**Comment by marksreeves** [comment]
We have promised this to an existing consumer and it is required in a release before the end of 2015.

**Comment by jonathanaustin** [comment]
Fixed loading WSubMenus via AJAX.

Items can now be dynamically added when the WSubMenu is opened. 

Menu components now hold their child items in a Container and can be accessed via the getMenuItems() method. This allows the AJAX to target the container and the child menu items added dynamically. 

Refer to #262.
