### ISSUE TITLE
WMenu API add getItems

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#262]
Offline enhancement request:

* add a method getItems to WMenu with the option to recurse through sub-menus.

**Priority**: _low_ (no specific use case with request)

**Comment by jonathanaustin** [comment]
WMenu API allows for getItems(boolean recursive).

Introduced new interfaces MenuItem, MenuItemGroup, MenuItemSelectable, MenuContainer and MenuSelectContainer to support and enhance the menu components.
