### ISSUE TITLE
Simplify WTable rowSelection select all/none control?

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#295]
WTable row selection allows select all/none controls as either a `text` or `control`. When `text` there are two controls which render without their button appearance; these controls are placed above the table's column headers. When `control` there is a toggle button with a tri-state checkbox appearance; this control is placed in the column header for the column which is a placeholder for the visual (secondary) indicator of the row's selected state.

I propose we do away with this and have only the `control` state (we would not need the enum at all). The `text` state is unusual, actually slightly harder to use (especially if keyboard driving as the controls are necessarily role radio) and rather ugly. Examples of each are [in the wiki](https://github.com/BorderTech/wcomponents/wiki/WTable).

What do we think? @ricksbrown @jonathanaustin @JohnMcGuinness

**Comment by JohnMcGuinness** [comment]
I agree that it would be an improvement to remove the `text`option.

**Comment by marksreeves** [comment]
Deferred indefinitely.
