### ISSUE TITLE
WCheckBoxSelect is there an easy way to get non selected?

### ISSUE THREAD

**Issue by Trentan** [BorderTech/wcomponents#296]
I don't think is really an issue, more being raised to improve my knowledge, maybe discussion in a forum would be more suitable.

Using .getSelected(), all selections are returned.
What if you want to use a WCheckBoxSelect in an include type format and omit easily.

ie:
Select your favourite ice cream flavours:
- [x] Chocolate
- [ ] Strawberry 
- [ ] Vanilla
- [x] Passionfruit
- [ ] Rainbow

.getSelected() would return Chocolate & Passionfruit.
new call (e.g. .getNonSelected() added to AbstractWMultiSelectList) would return Strawberry, Vanilla & Rainbow.

I know you can handle this at the moment with some conventional coding and using the existing .getSelected() statement.

If this is not an appropriate place to discuss please banish!

**Comment by marksreeves** [comment]
I think it is a reasonable idea so I will fag it as an enhancement. @jonathanaustin or @ricksbrown may have different views.

**Comment by jonathanaustin** [comment]
We could look at including a notSelectedOptions method.

But in the mean time....you could extend WCheckBoxSelect and implement your own method...
```java
public class MyCheckBox extends WCheckBoxSelect {
.....
  public List<?> getNotSelected() {
      List options = getOptions();
      if (options == null || options.isEmpty()) {
        return Collections.EMPTY_LIST;
      }

      List notSelected = new ArrayList(getOptions());
      notSelected.removeAll(getSelected());
      return Collections.unmodifiableList(notSelected);
  }
.....
}
```

**Comment by Trentan** [comment]
Thank you very much for the advice.

**Comment by JohnMcGuinness** [comment]
I really don't think it is worth it. It is trivial to get the non selected items as per @jonathanaustin's example above. It is also far more likely that you would want the selected items as opposed to the unselected items. @Trentan WDYT can this be closed?

**Comment by Trentan** [comment]
Fine with me, topic has been raised and I'm sure those looking for an answer in the future will find this post!

Thank you!
