### ISSUE TITLE
Create a HorizontalLayout

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#329]
@jonathanaustin has proposed to deprecate `FlowLayout` and replace it with a `HorizontalLayout`. It will be the same as a horizontal `FlowLayout`. According to @marksreeves the vertical `FlowLayout` 'can be constructed economically with `WPanel`' There will be no replacement for a vertical `FlowLayout`.

Proposed behaviour:
* A `HorizonalLayout` will, naturally, layout items horizontally. 
* It will allow a gap between the items to be set via a `spacing` property. 
* Items will wrap if they do not all fit horizontally. 
* Each item can be aligned using the `CellAlignment` enum.

Open questions:
* Should the cells be 'alignable', floating to the left, right or center?
* Should there be a space between rows if the items wrap? If so should it be configurable in the Java API?

WDYT @jonathanaustin @marksreeves @ricksbrown

**Comment by marksreeves** [comment]
Can I suggest we make more use of [gitter](https://gitter.im/BorderTech/wcomponents) to at least have a preliminary discussion of proposals before we create an enhancement issue?

**Comment by marksreeves** [comment]
Closed: we already have a horizontal layout and are moving away from rigid layout components.
