### ISSUE TITLE
Allow frontend devs to skip backend rebuilds and vice versa

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#40]
A java dev should not have to keep rebuilding client side code when they never change it.
A js dev should not have to keep rebuilding the java.

**Comment by marksreeves** [comment]
This can be done in Maven using the -pl (PapaLima) flag. For example from the `wcomponents-parent` root dir:
```
mvn -pl '!wcomponents-theme-parent,!wcomponents-theme' compile
```

Theme devs have it easy - just compile the wcomponents-theme or wcomponents-theme-parent project. If you want to do this from the wcomponents-parent dir, again the -pl flag comes into play, for example:
```
mvn -pl wcomponents-theme compile
```

**Comment by marksreeves** [comment]
@ricksbrown I am going to close this as resolved given the above answer to your original enhancement request. I am sure you will yell at me if it isn't.

**Comment by ricksbrown** [comment]
That's fine - I haven't had a chance to verify it yet but it sounds like it fits the bill. We can always reopen if we need to.
