### ISSUE TITLE
Allow WDialog to be triggered by an AjaxTrigger

### ISSUE THREAD

**Issue by antonweller** [BorderTech/wcomponents#407]
Is it possible to make the trigger for a WDialog an AjaxTrigger rather than a WButton? Then we could do client-side triggering of dialogs using WMenuItem.

This is the WDialog constructor for wcomponent-core-1.0.3 :
          public WDialog(final WComponent content, final WButton trigger) {
                   add(holder);

                   if (content != null) {
                             setContent(content);
                   }

                   this.trigger = trigger;

                   if (trigger != null) {
                             add(trigger);
                   }
          }

**Comment by marksreeves** [comment]
This is not going to happen for Q2 and is not required until November 2016 so I am rescheduling. Sorry.

**Comment by Joshua-Barclay** [comment]
With a little bit of crappy code this can be made as a trivial and backwards-compatible change in java.

The XSLT will be updated to support the current design, as well as supporting the mutually exclusive attribute indicating another element on the screen is the dialog trigger.

In java code, we can support both processes with the following:
WDialog.java
```java       
        private final WComponent trigger;
 
	public WDialog(final WComponent content, final AjaxTarget trigger) {
		add(holder);

		if (content != null) {
			setContent(content);
		}

		this.trigger = trigger;
		// trigger is NOT added to tree for AjaxTrigger - it will exist elsewhere
	}
	public WDialog(final WComponent content, final WButton trigger) {
		add(holder);

		if (content != null) {
			setContent(content);
		}

		this.trigger = trigger;
		// trigger is added to tree if button - old functionality
		if (trigger != null) {
			add(trigger);
		}
	}
```

WDialogRenderer.java
```java
                       if (dialog.getTrigger() == null) {
				xml.appendEnd();
			} else if (dialog.getTrigger() instanceof WButton) {
				xml.appendClose();
				dialog.getTrigger().paint(renderContext);
				xml.appendEndTag("ui:dialog");
			} else {
				xml.appendAttribute("triggerId", trigger.getId());
				xml.appendEnd();
                        }
```
