### ISSUE TITLE
WebUtilities.updateBeanValue(WComponent) should ignore non-visible components

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#46]
The standard approach within WComponents is that invisible components (component.isVisible() == false) are completely ignored from all phases of processing (e.g. validation, prepare paint component).

WebUtilities.updateBeanValue(Wcomponent) does not ignore invisible components and will invoke the update bean value method on the component and any children.

An overloaded method should be created with an additional boolean parameter specifying whether to ignore invisible components or not.

The default single-arg method should ignore invisible components, as this is the standard within the framework.

**Comment by jonathanaustin** [comment]
Yes, this behaviour has probably been in WComponents for a very long time. It is not consistent and should be fixed.

However, it will have a potential "knock on" affect to some applications if they were depending on this behaviour. For example, if applications were using a "card manager" to process a "wizard" like form, the invisible cards would have still been pushed to the beans. So with the fix, this will not occur by default and will fail silently. Applications will have to change their code to call the new method with "true" to process the invisible components.

We could consider having the fix as an "opt in" or at least issue a warning for the invisible components that are not processed.

**Comment by ricksbrown** [comment]
Closed by PR #108
