### ISSUE TITLE
Add compatibility layer for old property names

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#51]
Properties all renamed from `wcomponent.foo` to `bordertech.wcomponents.foo`

At least for a release or two we need to support the old property names a log a warning to indicate they are deprecated.

**Comment by Targe7** [comment]
Just a thought as this is relatively new project, i expect the existing consumers would be also using the ebiz config project.  If that is the case you could just supplied a them a mappings file containing mappings for the properties,  ie  bordertech.wcomponents.foo = ${wcomponent.foo} meaning you may get away without the main project supporting the old properties names.

**Comment by ricksbrown** [comment]
@SteveHarney Thanks for the suggestion it's a great idea and one we had not thought of. It's nice and simple and well worth considering. I think the only thing we'd lose is the deprecation warnings but they would probably never be needed.

@Joshua-Barclay would Steve's suggestion work for your application?

@jonathanaustin Thoughts on this?

**Comment by Joshua-Barclay** [comment]
Yes, Steve's proposed fix would work for us.

I think this is probably the lowest impact and most reliable workaround to support the old properties short term.

**Comment by jonathanaustin** [comment]
This would be a low impact workaround. 

We are providing an upgrade tool for the existing customers that will update their properties automatically. We will also review the environment properties to flag any "wcomponent" properties.

So I do feel providing the file would just prolong the "update" and there are not really that many properties to review and the tool will do it for them anyway. And as they have to run the tool for the package rename, their properties will get changed.

Let me know what you think. @ricksbrown @Joshua-Barclay @SteveHarney

**Comment by SteveHarney** [comment]
@jonathanaustin  I was actually thinking the same thing when i read Josh's comments.  it is a relatively straight forward job and they will have to change package names anyway. Make sure you take a look at the upgrade tool in reuse, i had done a bit of work on it before i left.

**Comment by ricksbrown** [comment]
@jonathanaustin I'm happy to rely on the upgrade tool and a bit of a manual review.
Based on the discussion I suggest we label this issue `wontfix` and close it.

**Comment by jonathanaustin** [comment]
I agree. As we are providing the upgrade tool we don't need this change.
