### ISSUE TITLE
PageReady for Automated Testing

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#536]
Currently automated testing tools can query the `data-wc-ajaxp` and `data-wc-timers` attributes on the body to determine if there are pending ajax or timeouts.

This level of granularity is not necessary - we should have one attribute `data-wc-domready` which is always present and starts out `false`. When there is no pending ajax or timers we should then set that to `true`.

**Comment by Joshua-Barclay** [comment]
Selenium testing has so far demonstrated that the new element `data-wc-domready` works correctly.

**Comment by ricksbrown** [comment]
@Joshua-Barclay Nice, thanks for the feedback. I'll close this.
