### ISSUE TITLE
Theme resources should not need to have a file extension

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#540]
[// all files should have a file suffix](https://github.com/BorderTech/wcomponents/blob/c43a86016fa3ae00a774e9cfecc3f0e8430bda77/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/servlet/ServletUtil.java#L371)
No, this is not true. 

We should be able to serve up resources that do not have a file extension.
For example [IANA timezone database files](http://www.iana.org/time-zones).

**Comment by marksreeves** [comment]
Fixed by #560
