### ISSUE TITLE
wcomponents-theme maven build fails if build directory has spaces in folder name

### ISSUE THREAD

**Issue by markoeronen** [BorderTech/wcomponents#56]
<i>eg. build directory </i>
C:\Documents and Settings\Marko\wcomponents
<i>resulting trace for</i> <b> mvn install</b>
....
init:
     [echo] build.xml basedir = C:\Documents and Settings\Marko\wcomponents\wcomponents-theme
    [mkdir] Created dir: C:\DOCUME~1\Marko\LOCALS~1\Temp\wcomponent-theme-tmp\implementations
    [mkdir] Created dir: C:\Documents and Settings\Marko\wcomponents\wcomponents-theme\target\tmp
     [echo] Build properties can be overriden in any of the following locations (in order of decreasing priority):
     [echo]   C:\Documents and Settings\Marko/.wc/Marko.xml (in user home dir)
     [echo]   C:\Documents and Settings\Marko/.wc/wc_theme_build_properties.xml (in user home dir)
     [echo]   C:\Documents and Settings\Marko\wcomponents\wcomponents-theme/Marko.xml (in the project root dir)
     [echo]   C:\Documents and Settings\Marko\wcomponents\wcomponents-theme/wc_theme_build_properties.xml (in the project root dir)
     [echo] npm install
     [echo]
     [echo]                             If npm hangs then make sure you have set your C:\Documents and Settings\Marko/.npmrc file correctly.
     [echo]
   <b>  [exec] 'C:\Documents' is not recognized as an internal or external command,</b>
     [exec] operable program or batch file.
     [exec] Result: 1
....
compileScss:
     [echo] node C:\Documents and Settings\Marko\wcomponents\wcomponents-theme\node_modules\node-sass\bin\node-sass C:\DOCUME~1\Marko\LOCALS~1\Temp\wcomponent-theme-tmp\wcomponents-theme\sass -o C:\DOCUME~1\Marko\LOCALS~1\Temp\wcomponent-theme-tmp\wcomponents-theme\css
     [exec] 'C:\Documents' is not recognized as an internal or external command,
....

**Comment by ricksbrown** [comment]
@markoeronen thanks for reporting this, it's definitely a bug in the build scripts.
