### ISSUE TITLE
White-space no longer honoured in WMessages

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#579]
WMessages is supposed to honour white space (pre-wrap). This has been lost.

**Comment by ricksbrown** [comment]
QC152874

**Comment by marksreeves** [comment]
This should not have been fixed. The old white-space rule is not in the Java API and was put in for a particular use case which involves the use of inaccessible text spacing to emulate a list. WMessageBox now allows HTML in the message so this white-space rule is no longer needed and may cause errors for applications correctly using HTML in WMessages. 

Therefore we should r very this change. The original issue internal to the consuming application should be resolved in that application as the use-case causes an accessibility problem.
