### ISSUE TITLE
WComponents Selenium Framework

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#605]
Selenium WebDriver works out of the box with WComponents (e.g. find by ID, tag, xpath), however some elements require intimate knowledge of the current client-side implementation. e.g. getting the title of a WDialog, or the pagination buttons for a table.

Ideally apps should be able to write tests that are unaware of the implementation details.
The best way we can do this is by writing a WComponent Selenium testing framework.

I am considering two possible implementations

**Option 1 - Wrap WebDriver**
This is the heavyweight option, but it is how Vaadin has solved the same problem.
We could create an implementation of Selenium WebDriver for WComponents that wraps the actual driver implementation. The wrapped driver could wrap WebElements as WCompWebElements and would provide an additional API to simplify access:
`WCompSeleniumTable table = driver.getTable(id);`
`WCompWebElement e = driver.getElement(id);`
**Pros:** Can automatically include the 'wait' code where needed. Intuitive for apps to use, requires almost no additional code. Can overload all 'find' methods to take WComponents as a parameter.
**Cons:** Highly coupled to Selenium implementation, more significant development effort.

**Option 2 - Static Utility Class**
The lightweight approach is to create a static utility class which will provide convenience methods:
`WCompSeleniumTable table = WCompSelenium.getTable(driver, id);`
`WCompSelenium.waitForPageReady(driver, timeout);`
**Pros:** low coupling with Selenium implementation, better suited to ad-hoc usage.
**Cons:** Less intuitive for apps, requires a lot of additional code

At the moment I am strongly leaning towards option 1. It will require more development effort but I believe it will be a better result for applications to use. We will also need to keep a close eye on Selenium updates to ensure the WComponent driver continues to support the full API.

@jonathanaustin @JohnMcGuinness @ricksbrown @marksreeves Comments welcome please.

**Comment by JohnMcGuinness** [comment]
I would definitely support option 1.

I disagree with Option 2 Pro regarding ad-hoc usage. I think that Option 1 when fully implemented would be easier to use for ad-hoc testing than option 1.

@jonathanaustin @ricksbrown @marksreeves @Joshua-Barclay

**Comment by ricksbrown** [comment]
Would it be feasible to do both like so:

1. Implement Option 2
2. Implement Option 1 by leveraging Option 2

In other words we write loosely coupled static utility classes but do not expect anyone else to use them but ourselves. Then we add the layer that is heavily coupled to selenium.
If something new comes along then we can swap out the selenium layer without losing everything.

**Comment by Joshua-Barclay** [comment]
@ricksbrown I don't think we can do that in a way that will achieve we want.

The tight coupling between our code and the Selenium API will come from writing a custom implementation of the `WebDriver` interface. Any calls made within our implementation will be invoking the wrapped Selenium implementation of the same `WebDriver` interface, so I don't think there's any benefit to de-coupling the implementation code.

If we were to split the code into two layers (_WebDriver API_ and _implementation_), we would still have to throw away and re-write both layers if we went away from Selenium.

**Comment by JohnMcGuinness** [comment]
I reality I think there is very little chance that any other tool will be replacing Selenium, even in the long term. So I don't think there's any problem with having the tight coupling with Selenium.

**Comment by Joshua-Barclay** [comment]
I'm more worried about API changes within Selenium. Option 1 will couple us pretty heavily to the current API and may require significant rework for future versions.

I believe this is worth the risk as it means we can provide an exceptionally simple and non-intrusive API for the WComponent specific features. I assume this is why Vaadin made the same decision.

**Comment by JohnMcGuinness** [comment]
[Selenium 3.0](https://github.com/SeleniumHQ/selenium/wiki/RoadMap) is slated for release soon.

**Comment by ricksbrown** [comment]
Ok seems reasonable... I was leaning to Option 2 but have not done much automation testing and since the consensus so far is Option 1 I'll agree that's the way to go.

Sounds like we should be targeting Selenium 3.0, I assume there are significant API changes with a new major version.

**Comment by JohnMcGuinness** [comment]
In relation to option 1 how about instead of:
```WCompSeleniumTable table = driver.getTable(id);```
```WCompWebElement e = driver.getElement(id);```
we do something like:
```UITable table = browser.find(UITable.with().id("my_table"));```
```UIElement e = browser.find(UIElement.with().id("my_element"))```

**Comment by JohnMcGuinness** [comment]
Some other examples:

```browser.find(UIButton.with().text("Ok")).click()```

```browser.find(UITextField.with().label("First name")).enter("John")```
```browser.find(UITextField.labeled("First name")).enter("John")```

**Comment by JohnMcGuinness** [comment]
Some other examples:

Textfield
```browser.find(UITextField.with().label("First name")).enter("John")```

```browser.find(UITextField.labeled("First name")).enter("John")```


Button
```browser.find(UIButton.with().text("Some text")).click()```

**Comment by Joshua-Barclay** [comment]
I've had a look at Selenium on GitHub and it doesn't look like there have been many changes to the WebDriver API in the past. It looks like there aren't major changes scheduled for Selenium 3.0 either.

I don't think it's likely we'll have to put too much effort into keeping synchronized with the Selenium API.

Regarding the method of finding components - Selenium already has an accepted pattern using the `By` interface. E.g. `ByID`. The WComponents solution should try to stick as close to the existing Selenium standards unless we have a compelling reason to diverge.

**Comment by JohnMcGuinness** [comment]
I don't see why we need to have an API that parallels the Selenium API @Joshua-Barclay. For example, the following example from Vaadin testbench which uses Selenium under the hood doesn't resemble the Selenium API:

```$(TextFieldElement.class).caption("Last Name").setValue("Durden");```

Its been created to make automating Vaadin as easy as possible.

To achieve the same for WComps as the above example for Vaadin, my example would be:

```browser.find(UITextField.labeled("Last Name")).enter("Durden")```

**Comment by JohnMcGuinness** [comment]
A larger example from [Vaadin testbench](https://vaadin.com/wiki/-/wiki/10674/Vaadin+TestBench+Tutorial)
```
@Test
public void testEnterNew() {
   getDriver().get("http://localhost:8080/");
   // 1. Click the "New" button
   $(ButtonElement.class).caption("New").first().click();

   // 2. Enter "Tyler" into the first name field
   $(TextFieldElement.class).caption("First Name").first().setValue("Tyler");

   // 3. Enter "Durden" into the last name field
   $(TextFieldElement.class).caption("Last Name").first().setValue("Durden");

   // 4. Click on some other row
   TableElement table = $(TableElement.class).first();
   table.getCell(6, 0).click();

   // 5. Assert that the entered name is not in the text fields any longer
   Assert.assertNotEquals("Tyler", $(TextFieldElement.class).caption("First Name").first().getValue());
   Assert.assertNotEquals("Durden", $(TextFieldElement.class).caption("Last Name").first().getValue());

   // 6. Click on the first row
   table.getCell(0,0).click();

   // 7. Verify that the first row and form contain "Tyler Durden"
   Assert.assertEquals("Tyler", table.getCell(0, 0).getText());
   Assert.assertEquals("Durden", table.getCell(0, 1).getText());
   Assert.assertEquals("Tyler", $(TextFieldElement.class).caption("First Name").first().getValue());
   Assert.assertEquals("Durden", $(TextFieldElement.class).caption("Last Name").first().getValue());
}
```

and in my proposed API:

```
@Test
public void testEnterNew() {

   Browser browser = getBrowser();
   browser.get("http://localhost:8080/");
   // 1. Click the "New" button
   browser.find(UIButton.labeled("New")).click();

   // 2. Enter "Tyler" into the first name field
   browser.find(UITextField.labled("First Name")).first().enter("Tyler");

   // 3. Enter "Durden" into the last name field
   browser.find(UITextField.labeled("Last Name")).first().enter("Durden");

   // 4. Click on some other row
   UITable table = browser.find(UITable.first());
   table.getCell(6, 0).click();

   // 5. Assert that the entered name is not in the text fields any longer
   Assert.assertNotEquals("Tyler", browser.find(UITextField.labled("First Name")).first().getText());
   Assert.assertNotEquals("Durden", browser.find(UITextField.labeled("Last Name")).first().getText());

   // 6. Click on the first row
   table.getCell(0,0).click();

   // 7. Verify that the first row and form contain "Tyler Durden"
   Assert.assertEquals("Tyler", table.getCell(0, 0).getText());
   Assert.assertEquals("Durden", table.getCell(0, 1).getText());
   Assert.assertEquals("Tyler", browser.find(UITextField.labled("First Name")).first().getText());
   Assert.assertEquals("Durden", browser.find(UITextField.labeled("Last Name")).first().getText());
}
```

**Comment by marksreeves** [comment]
Nothing to add technically but I would like to remind everyone:

Each time you think Selenium (or any other product) is here to stay: take a step sideways and think of it as an ActiveX control (or Flash, or Quicktime or even MySpace).

If we have to have a special layer to test our web applications maybe we have the wrong framework?

**Comment by Joshua-Barclay** [comment]
We don't _have_ to align with existing Selenium patterns, but it is preferred unless there's a strong reason to diverge. Aligning with industry standards will significantly reduce the learning curve for developers - the whole point of this wrapper project is that consumers should only have to know Selenium and not WComponents.

In this particular example, the `By` pattern has the following benefits:
1. Already has support for most use cases (e.g. ID, xpath, css)
2. Provides a straightforward way for us to implement custom WComponents selectors
3. Provides a straightforward way for applications to find our custom WComponents selectors
4. Applications with existing Selenium tests can continue to use them
5. Applications with existing custom selectors can continue to use them

I can't think of a compelling reason to use a builder-style pattern for a function that is mostly used in a very simple fashion. I'm happy to consider further if you think I've missed a compelling functional advantage.

**Comment by JohnMcGuinness** [comment]
Using ```By``` directly in a tests means that tests will be handling ```WebElement```s. Which to me would seem to be leaning more towards Option 2. see [ByVaadin](https://github.com/vaadin/testbench/blob/996de73c55d6081e593f46bd1e09674996c2b344/vaadin-testbench-core/src/main/java/com/vaadin/testbench/By.java)

Vaadin Testbench then adds its API on top of that.

**Comment by Joshua-Barclay** [comment]
Any custom `By` implementation can be overridden to return the specific subclass we want.

`public class WCompElement extends WebElement`
```
public class ByWcomponent extends By
{
  public WCompElement findElement(SearchContext context);
}
```

WebElements largely provide the API we need, it's only for some elements (table, dialog, field-set) that we might want to wrap them in a custom component.

**Comment by JohnMcGuinness** [comment]
It would still need to be cast to the particular type:

```WebElement el = driver.find(By.wcomponent())```

because WebDriver's find method returns a WebElement. So you would need to do this:

```WCompElement el = (WCompElement) driver.find(By.wcomponent())```

I would rather not have to cast.

**Comment by Joshua-Barclay** [comment]
We'll be implementing a WComponents specific version of `WebDriver`, so this won't be an issue.
We can override/overload methods such as `find(By)` to return the most appropriate type.

@marksreeves I agree with you that we should not bind ourselves too tightly to any specific implementation. WComponents does work out of the box with Selenium and doesn't technically need any wrapper/utility implementation. However, we have identified that a small effort from the WComponents team will significantly ease the burden of writing Selenium tests for applications. As it is _currently_ a widely accepted industry standard, it is worth the effort even if it is not necessarily a _permanent_ solution.

**Comment by Joshua-Barclay** [comment]
@rossrowe We'd appreciate your feedback on this issue as well. What do you think?

**Comment by rossrowe** [comment]
Creating a custom `By `selector sounds okay, but you'll probably need several to cater for selectors that the users wish to identify elements eg. `By.wcomponentWithId()`,` By.wcomponentWithName()`, `By.wcomponentWithXpath()`

In addition, `WebElement `is an interface, not a class, so creating an new implementation of this will mean you will have to implement all the methods defined by the interface. 

As an aside, we've been recently using [Fluentlenium](http://www.fluentlenium.org/) to write Selenium tests, and the code ends up being pretty reasonable.  It also supports [custom components](https://github.com/FluentLenium/FluentLenium#extend-fluentwebelement-to-model-components), so John's UITable example above would be something like this

```
UITable comp = findFirst("#my_table").as(UITable.class);
UIElement e = findFirst("#my_element")).as(UIElement.class);
```

**Comment by marksreeves** [comment]
The changes I am making to input components as part of #639 will break the current Selenium Element classes so I am self-assigning this for a while. If you are adding any new WComponents elements to the Selenium test suite in wcomponents-test-lib please prod me as part of your commit message (or beforehand).

**Comment by marksreeves** [comment]
PR #1084 included my changes to the WebElement extensions as noted above. It also added some new WebElement extensions. This is now in the current dev branch so my previous injunction is now lifted. Thanks for your patience.
