### ISSUE TITLE
Proactive WTable Action Constraints

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#618]
A `WTable` button can have a number of `ActionContraint`s that on press will display an error to the client if the condition is not met, e.g. no rows are selected.

In some circumstances it might be better to proactively disable/enable the button instead so the user knows that it is not a valid action given the current selection. This would be similar to how subordinate logic works at the moment.

@jonathanaustin @marksreeves  Thoughts?

**Comment by marksreeves** [comment]
I agree with this and was, in fact, how these actions were originally built. The UI designer at the time preferred the messages so that won. 

I support this change. I am aware of at least one long-term customer who would throw their support behind this too.

**Comment by marksreeves** [comment]
Over-fixed. Forgot we still need to allow warning actions.
