### ISSUE TITLE
Major version roadmap?

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#622]
We have a lot of deprecated code after 11 years of pretending to be Swing followed by 18 months of realising we build web apps.

I propose we set up a roadmap for a single release which clears out as much of the old deprecated code as possible. This will require a major release number update and should be scheduled for some time in 2017 but not in the three months before June 2017 (financial/legal year and all that).

This will involve some branch juggling in Git and mostly for @jonathanaustin. Given that most of the work will be deletion though we should not get ourselves into too much of a mess (I hope).

Can I please get input on this from all of you
@ricksbrown @Joshua-Barclay @JohnMcGuinness and anyone else interested.

**Comment by ricksbrown** [comment]
How DARE you imply that Swing is not the way of the future :rage:

I like the idea of a cleanup **but** there is so much else to do, realistically I'm not sure we'll get to it until we find some breathing room...

**Comment by JohnMcGuinness** [comment]
Just to clarify would this be 2.0.0. 

This would seem like a good opportunity to update the API to use Java 8, especially considering the time frames (late 2017) being considered. Almost all Java EE containers are now JEE 7 compliant, and by late 2017 it would be reasonable to expect that they all will be. However may be I'm being overly optimistic :disappointed:

**Comment by JohnMcGuinness** [comment]
Also, considering it is a major change would a 1.x.x branch be supported in parallel for a time to allow clients time to migrate?

**Comment by marksreeves** [comment]
This has now been resolved as V2 milestone.
