### ISSUE TITLE
Preload can cause JS load failure on iOS

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#629]
When 
1. a `wc/common` layer is used which results in the WAI-ARIA RDF and colormap XML being preloaded
2. the layer includes any ui modules
3. the platform is iOS; **and**
4. the preloaded resources are in cache;

then the `ui` modules _may_ not load resulting in, amongst other symptoms, the loading indicator getting "stuck".

**Comment by marksreeves** [comment]
This has all the hallmarks of a Safari/iOS prefetch bug. A link rel="prefetch" appears to block indefinitely when the resource is already in cache. If there are two or more of these then nothing else loads.

**Comment by marksreeves** [comment]
The issue may be related to i18n as well. The issue appears when resources are pre-loaded.

**Comment by ricksbrown** [comment]
The preload part of this seems to have been mostly a red herring but I'll pull out some superfluous parts.
The main issue seems to be with deeply nested ES6 Promises on iOS. They are hard to understand and debug anyways, replaced with good old fashioned callbacks on private functions where it doesn't affect the API anyway.

I suggest callbacks for private methods and promises for public API would be a good rule of thumb.
