### ISSUE TITLE
Subordinates should be able to set input values

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#643]
As the title says subordinates should be able to set input values. Because they cannot it results in excessive use of ajax controls. A project I am working on would be able to replace much of its ajax controls with subordinates if they could set values. Providing users with a much better user experience

@jonathanaustin @Joshua-Barclay @ricksbrown @marksreeves

**Comment by marksreeves** [comment]
Duplicate of #260
