### ISSUE TITLE
Properties files in Config vs Wiki

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#657]
The WComponents configuration wiki (https://github.com/BorderTech/wcomponents/wiki/Configuration-Properties) states that:
The next set of properties files which are loaded are application properties from files named `"wcomponents_app.properties"`. Applications wishing to configure WComponents using the internal configuration mechanism should place their WComponents properties in these files.

`com.github.bordertech.wcomponents.util.DefaultInternalConfiguration` specifies that properties are loaded from the following files:
```
	/**
	 * This array defines the file names which we load the internal configuration from, as well as the order in which
	 * the files are loaded.
	 */
	private static final String[] PARAMETER_LOAD_ORDER
			= {
				// The name of the first resource we look for is for internal properties
				"wcomponents.properties",
				// The name of the next resource we look at is for application properties
				"wcomponents-app.properties",
				// The last properties which are loaded are local/developer properties
				"local_app.properties"
			};
```

These values don't match (underscore vs dash). @jonathanaustin I would assume that the wiki is wrong here, given that applications may have implemented wcomponents-app.properties we would not want to break them.

Please confirm and I can make the change.

**Comment by marksreeves** [comment]
Anything in wiki was written by me and may well contain typographic errors. @Joshua-Barclay feel free to change the wiki, not the code, so that they match.

**Comment by marksreeves** [comment]
Fixed wiki entry
