### ISSUE TITLE
Default Selenium WebDriver Implementation to Headless Chrome

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#659]
There is currently work in progress to enable a headless mode in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=546953

It is already possible to build a headless executable from the Chrome source.

There is a further issue to support Selenium in this headless mode:
https://bugs.chromium.org/p/chromium/issues/detail?id=604324

Chrome is the most widely used browser and therefore should be considered an optimal default for WComponents testing. At the moment we do not use it as the default for Selenium due to the performance overhead of a non-headless browser.

Once Chrome supports a headless mode for Selenium testing it should be the default within WComponents.

**Comment by marksreeves** [comment]
> Once Chrome supports a headless mode for Selenium testing it should be the default within WComponents.

Until then this is a _nice to have_ so I am rescheduling it: sorry Josh!

**Comment by Joshua-Barclay** [comment]
@marksreeves @ricksbrown @jonathanaustin 
Chrome 59 has released with a headless mode (--headless). Someone should look at this issue again.

**Comment by ricksbrown** [comment]
Resolved in #1650 (except I defaulted to headless Firefox instead, so there).
