### ISSUE TITLE
Subordinate rule processing - read-only controls

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#780]
Components which implement SubordinateTrigger when in a read-only state (`component.isReadOnly() == true`) should process their subordinate rules _without_ reference to their disabled state.

A control in a readOnly state has a value which was immutable in the current view. It is a nonsense to `setDisabled(true)` on a control which is in a read-only state but nothing in the API prevents this so we have to make sure we ignore the disabled state when doing server-side subordinate rule processing on any control in a read only state.

This is a necessary precursor to #261.

**Comment by marksreeves** [comment]
@jonathanaustin Can you add a note here as to why you re-opened this. I have a vague idea in the chaos of my brain but need it clarified.

**Comment by jonathanaustin** [comment]
Item has been addressed.
