### ISSUE TITLE
Failes to compile in Java 8 due to JavaDoc issues

### ISSUE THREAD

**Issue by veenarm** [BorderTech/wcomponents#788]
I18nUtilities.java line 42 - @link on the resouce bundle text is breaking the build in java 8.
 (there is no actual link) maybe just remove the the @link as invalid use case?

There are also these two warnings.
[WARNING] /home/john/IdeaProjects/wcomponents/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/SimpleBeanBoundTableModel.java:603: warning - Tag @link: can't find LevelDetails(String, Class, boolean) in com.github.bordertech.wcomponents.SimpleBeanBoundTableModel.LevelDetails
[WARNING] /home/john/IdeaProjects/wcomponents/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/WTabGroup.java:130: warning - Tag @link: can't find addTab(WComponent, String, TabMode) in com.github.bordertech.wcomponents.WTabGroup

Refer to : http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

Doc Lint was added, and causes it to do extra checks, maybe disable in maven, or change to the above?

: Note - Also maybe add to the documentation minimum version of maven required? 3.1.1 - I had 3.0.5 and it failed builds :)

**Comment by marksreeves** [comment]
@jonathanaustin @Joshua-Barclay @ricksbrown 
I will fix the current crop (came about from the conversion of `com.github.bordertech.wcomponents.util.I18nUtilities.getResourceBundleBaseName()` to use the new `com.github.bordertech.wcomponents.util.ConfigurationProperties` class). **However**: we have to get a Java 8 automated build going.
