### ISSUE TITLE
Provide access to HTTPRequest

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#803]
The Request interface does not provide access to the backing request. We have had to modify this several times to provide access to request properties (such as specific headers) and we have a need to provide information about the user agent, platform etc as exposed in the request. 

We could expose all headers individually but this would not account for custom headers and seems a bit of a waste when we could expose the backing request.

**Comment by marksreeves** [comment]
We have also promised some consumers that we could provide a helper to determine if a request is coming from a mobile platform. This could be ascertained (as far as it is possible to do so) from the backing request but we should add a helper that does the heavy lifting so that multiple consumers do not have to do the same check for themselves.

**Comment by jonathanaustin** [comment]
The `Request` interface is a throw back to `Portal`. WComponents had to process two different types of requests, a `PortalRequest` or `HttpServletRequest`. As we no longer support `Portal` we could look at removing this abstraction layer.

This would be a major API change so would have to wait until Q4.

In the mean time, we can add a method to `ServletRequest` to provide access to the backing `HttpServletRequest`.

We can also provide a new helper method in `ServletUtil` to determine the user's device type.

**Comment by marksreeves** [comment]
Sounds like a plan. I have rescheduled.

**Comment by jonathanaustin** [comment]
There is value in maintaining the abstraction layer of our own `Request` and `Response` layers as `WComponents` may not always be running in a `Servlet` environment. It could be running in a non Java JVM such as `JRuby`, `Jython`, `Closure` or `Scala`.

Therefore, the lifecycle processing of `WComponents` should not be dependant on `HttpServletRequest` and `HttpServletResponse`.

**Comment by marksreeves** [comment]
I am closing this as resolved. @jonathanaustin did as much as we can, and solved the original enhancement request, by creating `ServletRequest#getBackingRequest()`.

@jonathanaustin feel free to re-open if you feel this is insufficient.
