### ISSUE TITLE
Default config for WTextArea in rich text mode strips formatting of left, center or right aligned text

### ISSUE THREAD

**Issue by JohnMcGuinness** [BorderTech/wcomponents#825]
I think it is reasonable for a user to assume that sanitization of any formatting created via WTextArea will remain intact after submitting the content of a WTextArea.

**Comment by marksreeves** [comment]
Yep, you are right. My original Policy had these but they obviously got lost along the way. I will get a fix in asap.

**Comment by JohnMcGuinness** [comment]
This is also an issue for superscript and subscript formatting.

**Comment by marksreeves** [comment]
hmmm, I would be more inclined to remove sub/super from the default tool set than to allow them in a default policy. Thanks. I thought I had caught everything but my multitude of Policies has obviously come back to bite me.

**Comment by JohnMcGuinness** [comment]
I think super/subscript would rarely be used, and not really missed if it was not available.

**Comment by marksreeves** [comment]
I would miss them: but I would miss `MathML` and no-one _really_ wants that!
