### ISSUE TITLE
Improve mechanism to add multiple HTML class attribute values

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#856]
AbstractWComponent has a member `private String htmlClass` which holds a single String which can be used to add additional class attribute value(s) to a component's output HTML. To add new value(s) we currently have to get the current value (if any), append a space then append the additional value(s); then use this concatenated String as the argument for `setHtmlClass(String)`. If one or more of the new values are from the `HtmlClassProperties` enum then we have to manually call `toString()` on those before we can use them. 

This should be made easier by either:

1. providing methods to do this without having to get and append spaces; or
2. by using a List<String> instead of a simple String member.

The first is quick (and a bit dirty) the second has a performance hit but can then also be leveraged to prevent the same value being added more than once and to remove value(s).

@jonathanaustin WDYT?

**Comment by JohnMcGuinness** [comment]
Point 2 should use a java.util.Set so that uniqueness is handled automatically.

Perhaps there should be methods called ```addHtmlClass(String)``` and ```removeHtmlClass(String)``` to make it clear that there is a collection of HTML classes that can be manipulated? Maybe even ```addAllHtmlClasses(String...)``` for adding more than one class value.
