### ISSUE TITLE
Security vulnerability with new windows

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#885]
https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c#.39htq6rme

Opening an external link in a new window provides the external page with the `window.opener` API to access the originating page. The `window.opener` api can be used to redirect the originator to another page which is a security vulnerability.

The issue can be addressed by setting `rel=noopener` in the outbound link.

**Comment by ricksbrown** [comment]
We currently don't use `window.opener` for anything as far as I can remember so yeah it would be no problem for us to blat the opener.

Google University reckons this "reverse tabnabbing" [is not worth attempting to work around](https://sites.google.com/site/bughunteruniversity/nonvuln/phishing-with-window-opener).

FYI we'd to add this: `rel="noopener noreferrer"` when building links or using `window.open`.
