### ISSUE TITLE
lock down specific versions of npm dependencies

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#91]
Currently we use the `^` syntax in our `package.json` which means newer versions will be pulled in automatically, for example: `"eslint": "^1.1.0"`

All but the most recent branch should certainly use specific versions of NPM dependencies otherwise older branches will potentially stop building and will certainly be unpredictable.

Actually even the most recent branch should probably nominate specific versions (as we already do in the maven `pom.xml` files).

**Comment by marksreeves** [comment]
Fixed versions gets my vote. 

Setting a specific version will cause a tiny maintenance overhead compared to the burden of 'fixing' the package at each point a release is made. The package.json can then be treated as any other versioned file and going back to version X will reset the dependencies.

**Comment by ricksbrown** [comment]
@marksreeves yes we should definitely lock dep versions in `release1`.
Regarding the active development branch (currently `release2`) I know where you are coming from when you suggest not locking the versions - ensuring we absorb the latest fixes and features from our dependencies.

The problem with this is it can break the build at unpredictable times - someone could fork WComponents to try it out and find it does not build, or a contributor could be unable to work on an issue.

I'd prefer to have more control over this.

As an interim for now I am going to experiment with switching from `^` versions to `~` versions. The difference is `^` will pick up every new minor or patch version while `~` will only pick up patch versions.
