### ISSUE TITLE
WTree AJAX expansion not working properly

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#934]
WTree is not handling the AJAX requests to open an item correctly.

For Horizontal trees, the expanded rows need to be set to the item being opened and its parent item ids.

For Vertical trees, the open item id should simply be added to the existing set of expanded rows.

**Comment by jonathanaustin** [comment]
Modify WTree that the client sends the full "open" state of the tree on the "open" request.

**Comment by marksreeves** [comment]
Fixed in #948
