### ISSUE TITLE
Investigate template options

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#94]
Currently WComponents supports the use of velocity templates. We could look at making it easier to use another templating tool as an alternative to component-tree based UI creation.

**Comment by marksreeves** [comment]
WComponents expects to be the root level element in the output tree. This is _only_ because it allows us to optimise performance in the XSLT layer by removing the need for a lot of root-down tests.

I have provided an XSLT-only theme which allows ui:root to be placed within an existing template (so long as the template has the requisite processing instruction to get the XSLT). This is intended to be a start point for any implementation which requires this type of template nesting and can be found at [wc-theme-anywhere](https://github.com/marksreeves/wc-theme-anywhere). This XSLT is closely based on the XSLT which used to exist in WComponents for precisely this purpose. It was removed quite recently to optimise performance for all existing use-cases as noted above.

Given the speed of XSLT processing (especially if using a specialised device) the extra processing overhead could be extraordinary small.

**Comment by marksreeves** [comment]
@ricksbrown has added [Moustache](https://mustache.github.io) JavaScript support to the theme as part of addressing #151. This _could_ be used in conjunction with Velocity to provide for mixed template/component tree applications. It is a long way from a final solution for this issue but worth noting. Perhaps @jonathanaustin or @JohnMcGuinness would care to take a look at [the Java API](https://github.com/spullara/mustache.java).

**Comment by marksreeves** [comment]
@jonathanaustin has a working implementation to address this.

**Comment by jonathanaustin** [comment]
Created a new WTemplate component that supports velocity, handlebars and plain text. Projects can also implement their own templating engines.

**Comment by marksreeves** [comment]
Finalised by #402
