### ISSUE TITLE
Datefield/PartialDateField polyfill calendar missing day names

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#942]
The single letter day name abbreviations are missing from the calendar.

**Comment by marksreeves** [comment]
@ricksbrown looks like the handlebars helper function is not being invoked in `wc/ui/calendar.js` line 504. I am happy to take a look at it if you don't have an immediate idea why.

**Comment by ricksbrown** [comment]
@marksreeves oh right, i think in handlebars we might have to register the helper properly, i'll take a look
