### ISSUE TITLE
WDialog not handling open state correctly

### ISSUE THREAD

**Issue by jonathanaustin** [BorderTech/wcomponents#963]
`WDialog` is not changing its `state` to `inactive` when it is part of a `dynamic` tab. This is causing it to open when the `tab` is reopened.

`WDialog` needs to check in `preparePaint` if it is still part of the current `ajax operation`. If it is no longer the active `ajax operation` then set its state to `inactive`.

For `WDialogs` that are manually opened (instead of using a trigger) a new `state` of `MANUAL_OPEN_STATE` has been introduced when `WDialog.display()` is called. This is needed so that in `preparePaint` a manually opened `WDialog` can be set to `active` even thought the`WDialog` is not part of the current `ajax operation`.

**Comment by jonathanaustin** [comment]
To improve the api of `WDialog` a new interface `DialogOpenTrigger` has been created.

`WDialog` was accepting any `AjaxTrigger` as an open trigger. However, this allowed too many components that dont make sense to open a dialog (eg `WDropdown`). The `DialogOpenTrigger` interface is a marker interface and has only been added to `WButton` and `WMenuItem`.

`WDialog` also has a new trigger open action. When this action is set via `setTriggerOpenAction(action)` the action will be run when a `DialogOpenTrigger` has triggered a `WDialog` to open.

**Comment by marksreeves** [comment]
Fixed in #970
