### ISSUE TITLE
Allow module config for setting constants in JavaScript modules.

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#97]
We have a pile of theme-dependent constants in many of the JavaScript UI modules. Some of these currently allow theme override using ANT property replacement at build time.

I suggest we add the facility to use RequireJs module.config() to allow implementations to override these constants rather than using ANT properties. This would, further down the track, allow overrides in templates for those config options which are used late enough.

**Comment by ricksbrown** [comment]
Yeah using RequireJS config instead of build time properties sounds like a good idea.
