### ISSUE TITLE
404 for some handlebars resources in some browsers

### ISSUE THREAD

**Issue by ricksbrown** [BorderTech/wcomponents#995]
[Yandex Browser](https://browser.yandex.com/desktop/) and [iOS9](https://support.apple.com/en-us/HT206568) appear to be incorrectly requesting handlebars resources, no doubt this is something to do with requirejs. 

Since iOS10 has replaced iOS9 and Yandex has small market share we are currently not treating this issue as a matter of urgency.

**Comment by ricksbrown** [comment]
I tried in Yandex 16.10.1.1116 and could not replicate any 404s.

**Comment by ricksbrown** [comment]
Tried on iOS 9.3 and could not replicate any 404s.

**Comment by marksreeves** [comment]
I used iOS 9 almost exclusively until it was updated and have an iPad still running iOS 9. I have not been able to replicate this issue. Where did it come from?

**Comment by marksreeves** [comment]
I have done more testing using iOS 9.3.4 and cannot replicate. Not closing yet but re-scheduling commensurate with its priority.

**Comment by marksreeves** [comment]
Still unable to replicate and the JavaScript import fixes which were part of PR #1084 will reduce any likelihood of unwarranted resource requests so I an closing this. @ricksbrown feel free to re-open if you ever get a positive replication.

**Comment by ricksbrown** [comment]
@marksreeves agreed, could not replicate. Let's reopen it if we hear any more reports.
